import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Almarai } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });
const almarai_init = Almarai({
  subsets: ['arabic'],
  weight: ['300','700'],
  variable: '--font-almarai'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={almarai_init.className}>
        {children}
        </body>
    </html>
  );
}
